### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by suhlig** [qudini/concourse-http-jq-resource#8]
I just used this resource to discover new versions of a rubygem (which seems not to be possible with the [rubygems-resource](https://github.com/troykinsella/concourse-rubygems-resource)).

My configuration is:

```yaml
- name: httpspell-gem
  type: http-jq-resource
  source:
    base_url: https://rubygems.org/api/v1/gems/httpspell.json
    jq_filter: "{version: .version}"
```

Contrary to the documentation, the discovered version _is_ actually available in a get step, so that I can load it as build variable:

```yaml
- load_var: httpspell-gem-version
  file: httpspell-gem/version
  format: json
```

and then make use of it as `((.:httpspell-gem-version.version))`.

Thanks a lot for this resource, and keep up the good work!

PS: Feel free to close this issue after reading.
